/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"E:\BeelinkerCode\CC2640F128\blelib\host\host_xxxo.a"
"E:\BeelinkerCode\CC2640F128\blelib\ctrl\cc2640\cc2640_ctrl_xxxo.a"
"E:\BeelinkerCode\CC2640F128\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none.a"
